os:
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9.3
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - bash test.sh
notifications:
  email: false
